# Generated by Django 5.0.1 on 2024-03-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='annee',
            new_name='date_sortie',
        ),
    ]
