# Generated by Django 5.0.1 on 2024-03-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_salles_remove_films_id_alter_films_date_sortie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_diffusion', models.TimeField()),
                ('date', models.DateField()),
                ('places_vendues', models.IntegerField(default=0)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.films')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.salles')),
            ],
        ),
    ]
