# Generated by Django 5.0.1 on 2024-03-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_seance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together={('salle', 'date', 'heure_diffusion')},
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_diffusion',
            field=models.CharField(max_length=5),
        ),
        migrations.RemoveField(
            model_name='seance',
            name='places_vendues',
        ),
    ]
