# Generated by Django 5.0.1 on 2024-03-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_seance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='places_vendues',
            field=models.IntegerField(default=0),
        ),
    ]
