# Generated by Django 5.0.1 on 2024-03-26 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_seance_places_vendues'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_diffusion',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.films')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.salles')),
            ],
        ),
    ]
