# Generated by Django 5.0.1 on 2024-03-26 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_seance_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
