# Generated by Django 5.0.1 on 2024-03-26 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_delete_reservation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together={('salle', 'date', 'heure_diffusion')},
        ),
    ]
