# Generated by Django 5.0.1 on 2024-03-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_seance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
