# Generated by Django 5.0.1 on 2024-03-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_alter_seance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='heure_diffusion',
            field=models.CharField(max_length=5),
        ),
    ]
