# Generated by Django 5.0.1 on 2024-04-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_films_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='duree',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_diffusion',
            field=models.IntegerField(),
        ),
    ]
