# Generated by Django 5.0.1 on 2024-04-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_alter_films_duree_alter_seance_heure_diffusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='duree',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_diffusion',
            field=models.CharField(max_length=5),
        ),
    ]
