# Generated by Django 5.0.1 on 2024-04-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_alter_films_duree_alter_seance_heure_diffusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='technologie',
            field=models.CharField(choices=[('Numérique', 'Numérique'), ('3D', '3D'), ('IMAX', 'IMAX'), ('4DX', '4DX')], default='Numérique', max_length=10),
        ),
    ]
