# Generated by Django 5.0.1 on 2024-04-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_films_technologie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='duree',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='seance',
            name='heure_diffusion',
            field=models.TimeField(),
        ),
    ]
