# Generated by Django 5.0.1 on 2024-04-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_alter_films_duree_alter_seance_heure_diffusion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='age',
        ),
    ]
