# Generated by Django 5.0.1 on 2024-04-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salles', '0002_delete_salles'),
    ]

    operations = [
        migrations.CreateModel(
            name='salles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.IntegerField()),
                ('technologie', models.CharField(choices=[('Numérique', 'Numérique'), ('3D', '3D'), ('IMAX', 'IMAX'), ('4DX', '4DX')], max_length=10)),
                ('prix_ticket', models.FloatField()),
            ],
        ),
    ]
