# Generated by Django 5.0.1 on 2024-04-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salles', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salles',
        ),
    ]
